### PR TITLE
[ADD] New style manage of speed fan.

### PR DESCRIPTION
**Pull request by byod0**
ADD Style Linear, is an "y = ax + b" function.
      Mini temperature is 1% fan speed
      Maxi temperature is 100% fan speed
      another value of temperature is compute by function linear between mini maxi
      
      I completed minimal documentation.

### CODE REVIEW

**Comment by adamoutler** [comment]
How much testing has been done on this? Could I see you some screenshots of the settings, the log, and the sensor? One of the key points I've tried to in-state with this project is that it is very conceptually simple.


I like the idea. Maybe we can even figure out how to remove the old methods and replace it with the new one. Since this one only requires two temperature settings instead of three, it has a lot of merit. But I want to do it right.

**Comment by byod0** [comment]
Hello, 
Juste testing on my personnal HA, (docker RPI4, 8gon 120go SSD + Argon)

**Log:** 
Capture d’écran du 2022-01-15 11-51-52

**Sensors:**
i have the same sensor. 
But locally i have : 
Capture d’écran du 2022-01-15 13-56-55
i don't know why.
I don't use this for the moment.

**Params:**
Capture d’écran du 2022-01-15 14-05-11

I keep old params, to keep two modes of manage speed fan.
Needed params is:
LowRange (rename to Temp Mini)
HighRange (rename to Temp Maxi)
CorF
==========================
QuietProfile not need

I remove mdi:speed-fan-x in sensor. 
With linear function, i not same logic. 

Do you need i remove old code ? to keep only "linear" computation ?

Thank you for your answer.

**Comment by adamoutler** [comment]
I'm sorry, I thought I responded to this.   I can remove the old code.  But you need to support QuietProfile.  The one problem that needs to be worked out is how to do a non-linear increase.   The Quiet Profile uses 1%, 3% and 100% because the chasis is so restrictive, 3% is like 50% of the total airflow possible.  We would need to replicate this feature.  eg.
image

The command line tool awk has this capability, but that would launch a new process every 30 seconds.  Currently the project only launches a process when it reads the initial json values, when it needs to change the fan speed, or when it needs to adjust the sensor value in Home Assistant.   This is the absolute minimum possible as i2c, json parsing, and networking require resources outside of BASH. 

It would absolutely be better to calculate a straight-math operation in BASH 50-100 times every 30 seconds than to launch a new process every 30 seconds.   It may also be possible to pre-calculate all the temperature and fan speed steps at the start, then compare the current temperature to find the first lower temperature in the array, and find the corresponding setting in the steps array. 

You seem like a mathy algorithmic type guy.  What do you think?

**Comment by byod0** [comment]
1/ We can use "y=ax^2+b" to generate logaritmic logic. i don't think is a problem.

2/ So, i don't think it's useful to have 100 call in 30s... because value returned in ".../thermal0" is integer, not float
ex: 3400, 3500, 2700... you can't have 34,76 C°, then, 30s is ok for me... temperature stabilized in normal environement don't +2, +3  points in 3s up or down. 

3/ I don't see difference to pre-calculate values or calculate value directly in loop ?
in pre calculate, you need to compare in multiple case; case1,case2,caseN > case100 ? i'm not sur to understand your explaination (i'm french), i don't think is lighty ? may be, i don't know, (we can to check)

4/ About sensors, i try to understand this:
"... and networking require resources outside of BASH"
there is a problem update sensors via POST request every 30s ?

**Comment by adamoutler** [comment]
If you can work out the math on the algorithmic method, it would be preferable. I'm not very good with the math on this.   I think we have to work out the calibration of stepping and limiting.

so fanspeed=((currentTemp^steppingFactor+lowTemp)x)-100


A lookup table of two arrays may prove conceptually simpler where, to initialize: 
`fanspeed` is an array of 100 integers.
`temp` is an array of 100 integers
`fanspeed=[0 ... 100]`
`tempsteps=highTemp/lowTemp/100`
`temp = [low temp, previous value+tempsteps, previous value+tempsteps ... 100th value]`

to run:
iterate each temp[] until currentTemp<=temp[n], and apply fanspeed[n].


No problem unless there's a more efficient way to do it.  We have to make process calls for JSON, networking and i2c.  I don't see another way around it.  I used the most basic methods possible such as using netcat instead of the more heavyweight curl.  I'd like to avoid using AWK if BASH is capable in a round-about way.   This problem would be easy to do in `awk` or in `expr`, but they are processes and that consumes resources, which in turn adds heat.  It's best to use bash unless absolutely necessary.

**Comment by adamoutler** [comment]
Good catch.  How do we get the ramp to work though?

**Comment by adamoutler** [comment]
I really like this, but we need a way to do a curved ramp for quiet profile so it is more clear and functionality is not expected but not present.

**Comment by byod0** [comment]
Hi. Sorry dont have lot of time.
But its complicated to resolve :
ax^2 + bx + c... To have logarithmic fonction.
Without take more CPU every 30s to compute RPM.

Its more simple to have fields with specific params quiet.

Quiet (1%) :50c to 55c

Rest is linear fonction:

(2% to 100%) 56c to 70c

Three fields... On for quiet, two for param ramp.




Le mar. 15 mars 2022 à 13:14, Adam Outler ***@***.***> a
écrit :

**Comment by adamoutler** [comment]
That was my analysis as well. 

If we remove the medium, I suppose it would be possible to tune the values between 1 and 100% to form a sort of quiet profile.  I suppose we should do that.   Let's do a full conversion. No more QuietProfile setting and no more medium. I'll handle docs update when you're done. 

The 3-stage setup was chosen because that's what Argon did.   This method is better and since the ranges are totally possible this works better. 

We will need to ensure the fan comes on at a min value of 3 out of 254.   This will ensure it has sufficient force to spin without binding and causing heat/stress on the fan component.

**Comment by adamoutler** [comment]
Hey,.  I think I have a solution. We can release an Argon One Active Linear Cooling.    If you would, please create a new folder, duplicating the  `argonOne` folder named `argonOneLinear`.  Add in the modified files and I'll accept the pull request, then link things in place, add the necessary config & repository files, then maintain it for future versions. The repo will then have the standard and linear versions.

**Comment by adamoutler** [comment]
I've added this as a second add-on.

**Comment by adamoutler** [comment]
New addon is integrated.  There are now two Addons
image
If you'd like to have a separate image, please feel free to upload.   I removed settings from the standard ArgonOne, and made all the changes I've wanted to make to the naming conventions.   I rewrote the docs for clarity and added pics. I think it's pretty smooth. 
image

**Comment by byod0** [comment]
Thanks you, i work on it when i found Time. !! :)

Le dim. 19 juin 2022 à 19:48, Adam Outler ***@***.***> a
écrit :

**Pull request merged**
